EVENT_SETUP_NEW = "setup_new"
EVENT_ENTRY_CONFIRMED = "entry_confirmed"
EVENT_LEVELS = "levels"
EVENT_TRADE_CLOSED = "trade_closed"
EVENT_SETUP_CANCELLED = "setup_cancelled"
EVENT_STATUS = "status"
EVENT_DAILY_SUMMARY = "daily_summary"
EVENT_WEEKLY_SUMMARY = "weekly_summary"
EVENT_WARNING = "warning"
EVENT_ERROR = "error"

EVENTS = {
    EVENT_SETUP_NEW,
    EVENT_ENTRY_CONFIRMED,
    EVENT_LEVELS,
    EVENT_TRADE_CLOSED,
    EVENT_SETUP_CANCELLED,
    EVENT_STATUS,
    EVENT_DAILY_SUMMARY,
    EVENT_WEEKLY_SUMMARY,
    EVENT_WARNING,
    EVENT_ERROR,
}

SIDE_LONG = "long"
SIDE_SHORT = "short"

SIDES = {SIDE_LONG, SIDE_SHORT}

CLOSE_TP = "tp"
CLOSE_SL = "sl"
CLOSE_MANUAL = "manual"
CLOSE_EXPIRED = "expired"
CLOSE_CANCELLED = "cancelled"

CLOSE_REASONS = {
    CLOSE_TP,
    CLOSE_SL,
    CLOSE_MANUAL,
    CLOSE_EXPIRED,
    CLOSE_CANCELLED,
}

WARNING_MISSED_CANDLES = "missed_candles"
WARNING_API_ERROR = "api_error"
WARNING_STALE_DATA = "stale_data"
WARNING_SIGNAL_NOT_CONFIRMED = "signal_not_confirmed"
WARNING_RISK_TOO_HIGH = "risk_too_high"
WARNING_POSITION_ALREADY_OPEN = "position_already_open"
WARNING_UNKNOWN_EVENT = "unknown_event"

WARNING_TYPES = {
    WARNING_MISSED_CANDLES,
    WARNING_API_ERROR,
    WARNING_STALE_DATA,
    WARNING_SIGNAL_NOT_CONFIRMED,
    WARNING_RISK_TOO_HIGH,
    WARNING_POSITION_ALREADY_OPEN,
    WARNING_UNKNOWN_EVENT,
}

ERROR_TYPES = WARNING_TYPES

DEFAULT_SYMBOL = "—"
DEFAULT_TIMEFRAME = "—"
DEFAULT_CURRENCY = "USDT"
